-- ============================================================
-- Interview Handbook DB schema
--
-- This project now shares the unified schema with Code Battle.
-- The canonical schema lives at:
--   code-battle/db/schema.sql
--
-- It includes all tables for both apps:
--   users, problems, problem_test_cases, matches, match_problems,
--   match_players, submissions, ratings,
--   user_topic_progress, user_preferences, user_progress_dashboard
--
-- To apply: run code-battle/db/schema.sql against your Supabase project.
-- ============================================================
