"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Play, RotateCcw } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

// ─── ConsoleOutput ────────────────────────────────────────────────────────────
function ConsoleOutput({ lines }: Readonly<{ lines: string[] | null }>) {
  return (
    <AnimatePresence mode="wait">
      {lines ? (
        <motion.div
          key="out"
          initial={{ opacity: 0, y: 4 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0 }}
          className="rounded-xl border bg-zinc-900 dark:bg-zinc-950 px-4 py-3 font-mono text-xs space-y-1 min-h-[52px]"
        >
          {lines.map((line, idx) => (
            <p key={`${idx}-${line}`} className="text-emerald-400">
              <span className="text-zinc-500 select-none mr-2">&gt;&gt;&gt;</span>
              {line}
            </p>
          ))}
        </motion.div>
      ) : (
        <motion.div
          key="ph"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="rounded-xl border bg-muted/20 px-4 py-3 min-h-[52px] flex items-center justify-center"
        >
          <p className="text-xs text-muted-foreground italic">Click ▶ Run to see output</p>
        </motion.div>
      )}
    </AnimatePresence>
  );
}

// ─── types ────────────────────────────────────────────────────────────────────
type ForLoopTopic = "iterate-list" | "range" | "enumerate-zip" | "dict-nested";

interface IterationStep {
  variable: string;
  value: string;
}

interface TopicInfo {
  label: string;
  color: string;
  badgeColor: string;
  description: string;
  codeSnippet: string;
  codeOutput: string[];
  iterationSteps: IterationStep[];
  iterationLabel: string;
}

// ─── data ─────────────────────────────────────────────────────────────────────
const topics: Record<ForLoopTopic, TopicInfo> = {
  "iterate-list": {
    label: "Iterate List",
    color: "bg-blue-500/15 border-blue-500/40 text-blue-700 dark:text-blue-300",
    badgeColor: "bg-blue-500/20 text-blue-700 dark:text-blue-300",
    description:
      "The for loop iterates over any iterable — lists, strings, tuples, and more. Each element is assigned to the loop variable one at a time.",
    codeSnippet: `# Iterate over a list
fruits = ["apple", "banana", "cherry"]
for fruit in fruits:
    print(fruit)

# Iterate over characters in a string
for char in "Python":
    print(char, end=" ")`,
    codeOutput: [
      "apple",
      "banana",
      "cherry",
      "P y t h o n",
    ],
    iterationSteps: [
      { variable: "fruit", value: '"apple"' },
      { variable: "fruit", value: '"banana"' },
      { variable: "fruit", value: '"cherry"' },
    ],
    iterationLabel: 'for fruit in ["apple", "banana", "cherry"]',
  },
  range: {
    label: "range()",
    color: "bg-emerald-500/15 border-emerald-500/40 text-emerald-700 dark:text-emerald-300",
    badgeColor: "bg-emerald-500/20 text-emerald-700 dark:text-emerald-300",
    description:
      "range() generates a sequence of numbers. It supports one, two, or three arguments: range(stop), range(start, stop), and range(start, stop, step).",
    codeSnippet: `# range(n) — 0 to n-1
for i in range(5):
    print(i, end=" ")

# range(start, stop)
for i in range(2, 7):
    print(i, end=" ")

# range(start, stop, step)
for i in range(0, 20, 5):
    print(i, end=" ")`,
    codeOutput: [
      "0 1 2 3 4",
      "2 3 4 5 6",
      "0 5 10 15",
    ],
    iterationSteps: [
      { variable: "range(5)", value: "0, 1, 2, 3, 4" },
      { variable: "range(2, 7)", value: "2, 3, 4, 5, 6" },
      { variable: "range(0, 20, 5)", value: "0, 5, 10, 15" },
    ],
    iterationLabel: "Number line generated by range()",
  },
  "enumerate-zip": {
    label: "enumerate() & zip()",
    color: "bg-violet-500/15 border-violet-500/40 text-violet-700 dark:text-violet-300",
    badgeColor: "bg-violet-500/20 text-violet-700 dark:text-violet-300",
    description:
      "enumerate() gives you both the index and the value. zip() lets you iterate over multiple iterables in parallel, pairing elements together.",
    codeSnippet: `# enumerate — index + value
colors = ["red", "green", "blue"]
for idx, color in enumerate(colors):
    print(f"{idx}: {color}")

# zip — parallel iteration
names = ["Alice", "Bob", "Charlie"]
scores = [85, 92, 78]
for name, score in zip(names, scores):
    print(f"{name} scored {score}")`,
    codeOutput: [
      "0: red",
      "1: green",
      "2: blue",
      "Alice scored 85",
      "Bob scored 92",
      "Charlie scored 78",
    ],
    iterationSteps: [
      { variable: "idx, color", value: "0, 'red'" },
      { variable: "idx, color", value: "1, 'green'" },
      { variable: "idx, color", value: "2, 'blue'" },
      { variable: "name, score", value: "'Alice', 85" },
      { variable: "name, score", value: "'Bob', 92" },
      { variable: "name, score", value: "'Charlie', 78" },
    ],
    iterationLabel: "enumerate() & zip() unpacking",
  },
  "dict-nested": {
    label: "Dictionary & Nested",
    color: "bg-orange-500/15 border-orange-500/40 text-orange-700 dark:text-orange-300",
    badgeColor: "bg-orange-500/20 text-orange-700 dark:text-orange-300",
    description:
      "Use .items() to iterate over dictionary key-value pairs. Nested for loops let you combine multiple iterations — useful for grids and tables.",
    codeSnippet: `# Dictionary iteration with .items()
person = {"name": "Alice", "age": 30, "city": "NYC"}
for key, value in person.items():
    print(f"{key}: {value}")

# Nested loop — multiplication table
for i in range(1, 4):
    row = ""
    for j in range(1, 4):
        row += f"{i*j:4}"
    print(row)`,
    codeOutput: [
      "name: Alice",
      "age: 30",
      "city: NYC",
      "   1   2   3",
      "   2   4   6",
      "   3   6   9",
    ],
    iterationSteps: [
      { variable: "key, value", value: "'name', 'Alice'" },
      { variable: "key, value", value: "'age', 30" },
      { variable: "key, value", value: "'city', 'NYC'" },
      { variable: "i=1, j", value: "1, 2, 3" },
      { variable: "i=2, j", value: "2, 4, 6" },
      { variable: "i=3, j", value: "3, 6, 9" },
    ],
    iterationLabel: "dict.items() & nested loops",
  },
};

const order: ForLoopTopic[] = ["iterate-list", "range", "enumerate-zip", "dict-nested"];

const chipColors: Record<ForLoopTopic, string> = {
  "iterate-list": "bg-blue-500/15 border-blue-500/40 text-blue-700 dark:text-blue-300",
  range: "bg-emerald-500/15 border-emerald-500/40 text-emerald-700 dark:text-emerald-300",
  "enumerate-zip": "bg-violet-500/15 border-violet-500/40 text-violet-700 dark:text-violet-300",
  "dict-nested": "bg-orange-500/15 border-orange-500/40 text-orange-700 dark:text-orange-300",
};

// ─── Main export ──────────────────────────────────────────────────────────────
export function ForLoopVisualization() {
  const [selected, setSelected] = useState<ForLoopTopic>("iterate-list");
  const [outputLines, setOutputLines] = useState<string[] | null>(null);
  const [activeStep, setActiveStep] = useState<number>(-1);
  const [isAnimating, setIsAnimating] = useState(false);

  const topic = topics[selected];

  const handleSelect = (key: ForLoopTopic) => {
    setSelected(key);
    setOutputLines(null);
    setActiveStep(-1);
    setIsAnimating(false);
  };

  const handleRun = () => {
    setOutputLines(null);
    setActiveStep(-1);
    setIsAnimating(true);

    const steps = topic.iterationSteps;
    steps.forEach((_, idx) => {
      setTimeout(() => {
        setActiveStep(idx);
      }, (idx + 1) * 400);
    });

    setTimeout(() => {
      setOutputLines(topic.codeOutput);
      setIsAnimating(false);
    }, (steps.length + 1) * 400);
  };

  const handleReset = () => {
    setOutputLines(null);
    setActiveStep(-1);
    setIsAnimating(false);
  };

  return (
    <Card>
      <CardHeader className="pb-3">
        <CardTitle className="text-lg">Python for Loop</CardTitle>
      </CardHeader>

      <CardContent className="space-y-5">
        {/* Topic selector chips */}
        <div className="flex flex-wrap gap-2">
          {order.map((key) => {
            const chipColor = chipColors[key];
            return (
              <button
                key={key}
                onClick={() => handleSelect(key)}
                className={`px-3 py-1.5 rounded-full text-xs font-semibold border transition-all ${
                  selected === key
                    ? chipColor + " scale-105 shadow-sm"
                    : "bg-muted/50 border-border text-muted-foreground hover:bg-muted"
                }`}
              >
                {topics[key].label}
              </button>
            );
          })}
        </div>

        {/* Animated detail area */}
        <AnimatePresence mode="wait">
          <motion.div
            key={selected}
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -8 }}
            transition={{ duration: 0.2 }}
            className="space-y-4"
          >
            {/* Description banner */}
            <div className={`rounded-xl border px-4 py-3 text-sm ${topic.color}`}>
              <div className="flex items-center gap-2 mb-1">
                <span className="font-bold font-mono text-base">{topic.label}</span>
                <Badge variant="secondary" className={`text-[10px] ${topic.badgeColor}`}>
                  for loop
                </Badge>
              </div>
              <p className="leading-relaxed opacity-90">{topic.description}</p>
            </div>

            {/* Two-column: iteration visual | code + output */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {/* Left: Iteration step visualization */}
              <div className="space-y-3">
                <p className="text-xs font-semibold text-muted-foreground">
                  Iteration Steps
                </p>
                <div className="rounded-xl border overflow-hidden">
                  {/* Header */}
                  <div className={`px-3 py-2 text-xs font-mono font-semibold ${topic.color}`}>
                    {topic.iterationLabel}
                  </div>

                  {/* Number line for range() */}
                  {selected === "range" && (
                    <div className="px-3 py-3 border-t">
                      {topic.iterationSteps.map((step, idx) => (
                        <div key={`range-line-${idx}-${step.variable}`} className="mb-2 last:mb-0">
                          <p className="text-[10px] text-muted-foreground font-mono mb-1">
                            {step.variable}
                          </p>
                          <div className="flex items-center gap-1">
                            {step.value.split(", ").map((num, nIdx) => (
                              <motion.div
                                key={`num-${idx}-${nIdx}-${num}`}
                                initial={{ scale: 0.8, opacity: 0.3 }}
                                animate={{
                                  scale: activeStep >= idx ? 1 : 0.8,
                                  opacity: activeStep >= idx ? 1 : 0.3,
                                }}
                                transition={{ delay: nIdx * 0.05 }}
                                className={`w-8 h-8 rounded-lg flex items-center justify-center text-xs font-mono font-bold border ${
                                  activeStep >= idx
                                    ? "bg-emerald-500/15 border-emerald-500/40 text-emerald-700 dark:text-emerald-300"
                                    : "bg-muted/30 border-border text-muted-foreground"
                                }`}
                              >
                                {num}
                              </motion.div>
                            ))}
                          </div>
                        </div>
                      ))}
                    </div>
                  )}

                  {/* Step rows for non-range topics */}
                  {selected !== "range" &&
                    topic.iterationSteps.map((step, idx) => (
                      <motion.div
                        key={`step-${idx}-${step.variable}-${step.value}`}
                        initial={{ opacity: 0.4 }}
                        animate={{
                          opacity: activeStep >= idx ? 1 : 0.4,
                          backgroundColor:
                            activeStep === idx
                              ? "rgba(59, 130, 246, 0.08)"
                              : "transparent",
                        }}
                        transition={{ duration: 0.3 }}
                        className="flex items-center gap-3 px-3 py-2 border-t text-xs font-mono"
                      >
                        <span className="text-muted-foreground w-4 text-right shrink-0">
                          {idx + 1}
                        </span>
                        <span
                          className={`shrink-0 ${
                            activeStep >= idx
                              ? "text-blue-600 dark:text-blue-400 font-semibold"
                              : "text-muted-foreground"
                          }`}
                        >
                          {step.variable}
                        </span>
                        <span className="text-muted-foreground">=</span>
                        <span
                          className={
                            activeStep >= idx
                              ? "text-emerald-600 dark:text-emerald-400"
                              : "text-muted-foreground"
                          }
                        >
                          {step.value}
                        </span>
                        {activeStep === idx && (
                          <motion.span
                            initial={{ scale: 0 }}
                            animate={{ scale: 1 }}
                            className="ml-auto text-blue-500"
                          >
                            ←
                          </motion.span>
                        )}
                      </motion.div>
                    ))}
                </div>
              </div>

              {/* Right: Code + Output */}
              <div className="space-y-3">
                <div>
                  <p className="text-xs font-semibold text-muted-foreground mb-1.5">Code</p>
                  <pre className="text-xs font-mono rounded-xl border bg-muted/40 px-4 py-3 whitespace-pre overflow-x-auto min-h-[120px]">
                    {topic.codeSnippet}
                  </pre>
                </div>
                <div className="flex gap-2">
                  <Button size="sm" onClick={handleRun} disabled={isAnimating}>
                    <Play className="h-3.5 w-3.5 mr-1" /> Run
                  </Button>
                  {(outputLines || activeStep >= 0) && (
                    <Button size="sm" variant="outline" onClick={handleReset}>
                      <RotateCcw className="h-3.5 w-3.5 mr-1" /> Reset
                    </Button>
                  )}
                </div>
                <div>
                  <p className="text-xs font-semibold text-muted-foreground mb-1.5">Output</p>
                  <ConsoleOutput lines={outputLines} />
                </div>
              </div>
            </div>
          </motion.div>
        </AnimatePresence>
      </CardContent>
    </Card>
  );
}
